### ISSUE TITLE
Nightmare runner error: TypeError

### ISSUE THREAD

**Issue by djmbritt** [segmentio/nightmare#1027]
So I'm trying out nightmare with the included test script, and and I keep getting stuck at on this point, TypeError: Cannot read property 'dock of undefined.
Could not find any other similair issues.

```DEBUG=* node test.js
  nightmare queuing process start +0ms
  nightmare queueing action "goto" for https://duckduckgo.com +6ms
  nightmare queueing action "type" +4ms
  nightmare queueing action "click" +0ms
  nightmare queueing action "wait" +1ms
  nightmare queueing action "evaluate" +0ms
  nightmare running +0ms
  nightmare running +106ms

Nightmare runner error:

        TypeError: Cannot read property 'dock' of undefined
            at Object.<anonymous> (~/projectFolder/node_modules/nightmare/lib/runner.js:58:29)
            at Module._compile (module.js:556:32)
            at Object.Module._extensions..js (module.js:565:10)
            at Module.load (module.js:473:32)
            at tryModuleLoad (module.js:432:12)
            at Function.Module._load (module.js:424:3)
            at Module.runMain (module.js:590:10)
            at run (bootstrap_node.js:402:7)
            at startup (bootstrap_node.js:157:9)
            at bootstrap_node.js:521:3
```
I am thinking that the issue is with electron, with the line const app = require('electron').app because the issue pops up when app.dock gets called.

Any ideas on how to resolve the issue?

Running on Mac 10.9, node v7.6.0, npm 4.3.0

**Comment by djmbritt** [comment]
I managed to fix it, I'm not completely sure why it's working now.
But when I was playing around with the options: show and frame for setting up the nightmare instance it started working properly.
