### ISSUE TITLE
Failing to run Nightmare.js as www-data

### ISSUE THREAD

**Issue by iget-esoares** [segmentio/nightmare#1045]
Hi,

I'm trying to run nightmare.js over an PHP Script executed by nginx/PHP-FPM.
Running the same command as root or any non www-data user works as expected.
But when running over www-data user, if fails since www-data user don't have a home directory:

```
Wed, 15 Mar 2017 18:52:54 GMT electron:stderr A JavaScript error occurred in the main process
Wed, 15 Mar 2017 18:52:54 GMT electron:stderr Uncaught Exception:
Wed, 15 Mar 2017 18:52:54 GMT electron:stderr Error: Failed to get 'appData' path
Wed, 15 Mar 2017 18:52:54 GMT electron:stderr     at Object.<anonymous> (/home/esoares/Sandbox/cdtsys/node_modules/electron/dist/resources/electron.asar/browser/init.js:149:39)
Wed, 15 Mar 2017 18:52:54 GMT electron:stderr     at Object.<anonymous> (/home/esoares/Sandbox/cdtsys/node_modules/electron/dist/resources/electron.asar/browser/init.js:173:3)
Wed, 15 Mar 2017 18:52:54 GMT electron:stderr     at Module._compile (module.js:571:32)
Wed, 15 Mar 2017 18:52:54 GMT electron:stderr     at Object.Module._extensions..js (module.js:580:10)
Wed, 15 Mar 2017 18:52:54 GMT electron:stderr     at Module.load (module.js:488:32)
Wed, 15 Mar 2017 18:52:54 GMT electron:stderr     at tryModuleLoad (module.js:447:12)
Wed, 15 Mar 2017 18:52:54 GMT electron:stderr     at Function.Module._load (module.js:439:3)
Wed, 15 Mar 2017 18:52:54 GMT electron:stderr     at Module.runMain (module.js:605:10)
Wed, 15 Mar 2017 18:52:54 GMT electron:stderr     at run (bootstrap_node.js:428:7)
Wed, 15 Mar 2017 18:52:54 GMT electron:stderr     at startup (bootstrap_node.js:147:9)
Wed, 15 Mar 2017 18:52:57 GMT electron:stderr Home directory not accessible: Permission denied
Wed, 15 Mar 2017 18:52:57 GMT electron:stderr libGL error: No matching fbConfigs or visuals found
Wed, 15 Mar 2017 18:52:57 GMT electron:stderr libGL error: failed to load driver: swrast
```

So I've tried changing Electron's path configuration as described to a folder that www-data has permissions (it's owner and 0777 chmod for testing), but the same error occurs, like my settings was not being used.

Here the relevant part of my script:

```
const path = require('path');
var Nightmare = require('nightmare');
var nightmare = Nightmare({
    show: false,
    paths: {
        home: path.resolve('../storage/tmp'),
    }
});

var url = process.argv[2];
var output = process.argv[3];

nightmare
    .goto(url)
    .wait()
    .pdf(output)
    .end()
    .then(function (result) {
        console.log('PDF File Generated successfully.');
    })
    .catch(function (error) {
        console.error('Search failed:', error);
    });
```

I'm running it over xvfb using this command:

```
DEBUG=* xvfb-run /usr/bin/node $scriptPath $html $pdfDestination >/tmp/nmerror.log 2>&1
```

If I run the same script with my own user, it works fine.

**Comment by johnferro** [comment]
@iget-esoares As documented [here](https://github.com/electron/electron/blob/master/docs/api/app.md#appgetpathname) there are both `home` and `appData` valid values for the paths option.  From the error you provided - `Error: Failed to get 'appData' path` - it seems like you might need to set that `appData` value in addition/instead of `home`.

**Comment by iget-esoares** [comment]
@johnferro I've tried both. My current -attempt- script now is:

```
var nightmare = Nightmare({
    show: false,
    paths: {
        home: path.resolve('../storage/tmp'),
        appData: path.resolve('../storage/tmp'),
    }
});
```

**Comment by iget-esoares** [comment]
Looking at line 122 of nightmare.js:

```
this.proc = proc.spawn(electron_path, [runner].concat(JSON.stringify(electronArgs)), {
      stdio: [null, null, null, 'ipc'],
      env: defaults(options.env || {}, process.env)
    });
```

Seems like the arguments are only set after electron being initialized, so electron try to write at home directory and fails before nightmare set the home directory...

**Comment by johnferro** [comment]
Hmmmm, yeah looks like the paths are being set in the [runner](https://github.com/segmentio/nightmare/blob/master/lib/runner.js#L39) which would be after electron gets initialized.

**Comment by iget-esoares** [comment]
I've found a way to solve this:

Overriding the `$HOME` before calling nightmarejs:

```
HOME=/desired/home/path DEBUG=* xvfb-run /usr/bin/node $scriptPath $html $pdfDestination >/tmp/nmerror.log 2>&1";
```

So electron with try to write at this home path, not at user's home path.

**Comment by matthewmueller** [comment]
hi @iget-esoares, thanks for the debugging information. One question I have is:

How are you trigger this error? What does the `path` in `pdf(path)` look like?
