### ISSUE TITLE
Error processing argument at index 0 when doing screen capture

### ISSUE THREAD

**Issue by maksimlikharev** [segmentio/nightmare#1063]
Nightmare: 2.10.0
Reproducible on MacOS, Amazon Linux

Not sure where the problem is.

```

        TypeError: Error processing argument at index 0, conversion failure from #<Object>
            at BrowserWindow.capturePage (/opt/reuters/apps/nodejs/node_modules/electron/dist/resources/electron.asar/browser/api/browser-window.js:19
7:44)
            at FrameManager.<anonymous> (/opt/reuters/apps/nodejs/node_modules/nightmare/lib/runner.js:424:23)
            at Object.onceWrapper (events.js:290:19)
            at emitOne (events.js:96:13)
            at FrameManager.emit (events.js:188:7)
            at Function.receiveFrame (/opt/reuters/apps/nodejs/node_modules/nightmare/lib/frame-manager.js:52:10)
```

**Comment by maksimlikharev** [comment]
ok, here is my findings, after I simplified to following action:


    Nightmare.action('capturePageImage',
     function(name, options, parent, win, renderer, done) {
         parent.respondTo('capturePageImage', function(clip, done) {
         win.webContents.capturePage(clip, function(image) {
         done(null, image.toPng());
       });
     });
     done();
    },
    function (clip, done) {
      this.child.call('capturePageImage', clip, function (error, img) {
        done(null, new Buffer(img.data));
      });
    });

In some cases image.toPng() returns null, so there are:
1. a nightmare bug, it must check for nulls ( new Buffer(img.data) ) and not blowout node instance.
2. a documentation point, according to this: https://github.com/electron/electron/issues/2548, image capture can only be done after: `did-finish-load`

**Comment by maksimlikharev** [comment]
closing this one, this is really all on electron side
