### ISSUE TITLE
How to use in Electron-application

### ISSUE THREAD

**Issue by kissarat** [segmentio/nightmare#1084]
Can I use Nightmare inside my Electron application? When I simply run
  ```const Nightmare = require('nightmare');

nightmare = Nightmare({show: true});

nightmare
  .goto('https://web.skype.com')
  .type('#username', 'blablabla')
  .wait(30000)
  .end()
  .catch(console.error);
```
I'v got an an error
  ```TypeError: Bad argument
    at ChildProcess.spawn (internal/child_process.js:289:26)
    at Object.exports.spawn (child_process.js:399:9)
    at Nightmare.queue (/Users/kissarat/project/app/node_modules/nightmare/lib/nightmare.js:123:22)
    at next (/Users/kissarat/project/app/node_modules/nightmare/lib/nightmare.js:341:12)
    at Nightmare.run (/Users/kissarat/project/app/node_modules/nightmare/lib/nightmare.js:331:3)
    at /Users/kissarat/project/app/node_modules/nightmare/lib/nightmare.js:492:10
    at Nightmare.then (/Users/kissarat/project/app/node_modules/nightmare/lib/nightmare.js:490:10)
    at Nightmare.catch (/Users/kissarat/project/app/node_modules/nightmare/lib/nightmare.js:506:15)
    at Object.<anonymous> (/Users/kissarat/project/app/main.js:21:9)
    at Object.<anonymous> (/Users/kissarat/project/app/main.js:69:3)
```
Is it tricky to rewrite some code to run inside Electron?

**Comment by stephenmathieson** [comment]
Can you try again with `DEBUG=nightmare* node yourscript.js` when you run the script? Much more helpful debugging messages will be sent to your console

**Comment by kissarat** [comment]
I run `DEBUG=nightmare* electron main.js` and I'v got
  ```
  nightmare queuing process start +0ms
  nightmare queueing action "goto" for https://web.skype.com +3ms
  nightmare queueing action "type" +1ms
  nightmare queueing action "wait" +0ms
  nightmare running +4ms
TypeError: Bad argument
    at ChildProcess.spawn (internal/child_process.js:289:26)
    at Object.exports.spawn (child_process.js:399:9)
    at Nightmare.queue (/Users/kissarat/project/app/node_modules/nightmare/lib/nightmare.js:123:22)
    at next (/Users/kissarat/project/app/node_modules/nightmare/lib/nightmare.js:341:12)
    at Nightmare.run (/Users/kissarat/project/app/node_modules/nightmare/lib/nightmare.js:331:3)
    at /Users/kissarat/project/app/node_modules/nightmare/lib/nightmare.js:492:10
    at Nightmare.then (/Users/kissarat/project/app/node_modules/nightmare/lib/nightmare.js:490:10)
    at Nightmare.catch (/Users/kissarat/project/app/node_modules/nightmare/lib/nightmare.js:506:15)
    at Object.<anonymous> (/Users/kissarat/project/app/main.js:30:9)
    at Object.<anonymous> (/Users/kissarat/project/app/main.js:71:3)

```

**Comment by stephenmathieson** [comment]
Ahh, just realized you're running the script under `electron`, not `node`. I have no experience doing that, sorry :/

**Comment by yum72** [comment]
Hi, I ran into this problem before and solved it by starting a child process for the nightmare code when it was needed. something like:

//inside electron
document.getElementById("startScraping").addEventListener("click", function () {
    var exec = require('child_process').exec;
    extractorProcess = exec('node your-nightmare-code.js ')
});

check this article for child process usage: http://krasimirtsonev.com/blog/article/Nodejs-managing-child-processes-starting-stopping-exec-spawn

**Comment by casesandberg** [comment]
Looks like this is resolved. I am going to close this for now but feel free to open a new issue if you are still having problems.
