### ISSUE TITLE
refresh() then inject() ?

### ISSUE THREAD

**Issue by stevenvachon** [segmentio/nightmare#1101]
```js
const browser = new Nightmare().goto('about:blank');
```
```js
browser.refresh().inject('file.js').evaluate(...);
```

This fails for me, with this error:

```
TypeError: done is not a function
 at Nightmare.exports.inject (node_modules/nightmare/lib/actions.js:534:5)
 at next (node_modules/nightmare/lib/nightmare.js:341:12)
 at Nightmare.run (node_modules/nightmare/lib/nightmare.js:331:3)
 at node_modules/nightmare/lib/nightmare.js:492:10
 at Nightmare.then (node_modules/nightmare/lib/nightmare.js:490:10)
```

This works, however:

```js
readFile('file.js', 'utf8')
    .then(lib => browser.refresh().evaluate( function(lib) {
        var script = document.createElement('script');
        script.innerHTML = lib;
        document.body.appendChild(script);
    }, lib))
    .then(() => browser.evaluate(...));
```

**Comment by stevenvachon** [comment]
Stupid me, it's `inject('js', 'file.js')`.
