### ISSUE TITLE
How to javascript errors?

### ISSUE THREAD

**Issue by agustim** [segmentio/nightmare#1137]
I try upload file to wetransfer.com with this script:

```javascript
const Nightmare = require('nightmare')
require('nightmare-upload')(Nightmare)
const nightmare = Nightmare({ show: true, typeInterval: 20})

nightmare
  .useragent('Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0')
  .goto('https://wetransfer.com')
  .wait('button.transfer__button')
  .click('button.transfer__button')
  .upload('div.uploader__files input','/absloute/path/file.ext')
  .type('input.uploader__textfield', "my@email.com")
  .type('input.uploader__textfield', "new@email.com")
  .click('div.transfer__footer button.transfer__button')
  .wait(60000)
  .end()
  .then(function (result) {
     done()
   })

```

But, if you open "Developer tools" I can see error:

`
cdn.wetransfer.net/assets/application-9a010fe19a400cdab6864b333504321f9460f3da30f22c05ed33455ea7699403.js:22 Uncaught TypeError: Cannot assign to read only property 'onbeforeunload' of object '#<Window>'
    at t.componentWillMount (cdn.wetransfer.net/assets/application-9a010fe19a400cdab6864b333504321f9460f3da30f22c05ed33455ea7699403.js:22)
    at c.performInitialMount (cdn.wetransfer.net/assets/application-9a010fe19a400cdab6864b333504321f9460f3da30f22c05ed33455ea7699403.js:22)
    at c.mountComponent (cdn.wetransfer.net/assets/application-9a010fe19a400cdab6864b333504321f9460f3da30f22c05ed33455ea7699403.js:22)
    at Object.mountComponent (cdn.wetransfer.net/assets/application-9a010fe19a400cdab6864b333504321f9460f3da30f22c05ed33455ea7699403.js:8)
    at c._updateRenderedComponent (cdn.wetransfer.net/assets/application-9a010fe19a400cdab6864b333504321f9460f3da30f22c05ed33455ea7699403.js:22)
    at c._performComponentUpdate (cdn.wetransfer.net/assets/application-9a010fe19a400cdab6864b333504321f9460f3da30f22c05ed33455ea7699403.js:22)
    at c.updateComponent (cdn.wetransfer.net/assets/application-9a010fe19a400cdab6864b333504321f9460f3da30f22c05ed33455ea7699403.js:22)
    at c.receiveComponent (cdn.wetransfer.net/assets/application-9a010fe19a400cdab6864b333504321f9460f3da30f22c05ed33455ea7699403.js:22)
    at Object.receiveComponent (cdn.wetransfer.net/assets/application-9a010fe19a400cdab6864b333504321f9460f3da30f22c05ed33455ea7699403.js:8)
    at Object.updateChildren (cdn.wetransfer.net/assets/application-9a010fe19a400cdab6864b333504321f9460f3da30f22c05ed33455ea7699403.js:22)
/myscript/nightmare/wetransfer/node_modules/nightmare/lib/preload.js:7 Uncaught TypeError: Cannot read property 'stack' of null
    at /myscript/nightmare/wetransfer/node_modules/nightmare/lib/preload.js:7:59
    at fn (<anonymous>:13:13)
    at javascript (<anonymous>:30:21)
    at <anonymous>:45:3
    at EventEmitter.electron.ipcRenderer.on (/myscript/nightmare/wetransfer/node_modules/electron/dist/resources/electron.asar/renderer/init.js:52:28)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
cdn.wetransfer.net/assets/application-9a010fe19a400cdab6864b333504321f9460f3da30f22c05ed33455ea7699403.js:22 Uncaught TypeError: Cannot read property '_currentElement' of null
    at c._updateRenderedComponent (cdn.wetransfer.net/assets/application-9a010fe19a400cdab6864b333504321f9460f3da30f22c05ed33455ea7699403.js:22)
    at c._performComponentUpdate (cdn.wetransfer.net/assets/application-9a010fe19a400cdab6864b333504321f9460f3da30f22c05ed33455ea7699403.js:22)
    at c.updateComponent (cdn.wetransfer.net/assets/application-9a010fe19a400cdab6864b333504321f9460f3da30f22c05ed33455ea7699403.js:22)
    at c.receiveComponent (cdn.wetransfer.net/assets/application-9a010fe19a400cdab6864b333504321f9460f3da30f22c05ed33455ea7699403.js:22)
    at Object.receiveComponent (cdn.wetransfer.net/assets/application-9a010fe19a400cdab6864b333504321f9460f3da30f22c05ed33455ea7699403.js:8)
    at c._updateRenderedComponent (cdn.wetransfer.net/assets/application-9a010fe19a400cdab6864b333504321f9460f3da30f22c05ed33455ea7699403.js:22)
    at c._performComponentUpdate (cdn.wetransfer.net/assets/application-9a010fe19a400cdab6864b333504321f9460f3da30f22c05ed33455ea7699403.js:22)
    at c.updateComponent (cdn.wetransfer.net/assets/application-9a010fe19a400cdab6864b333504321f9460f3da30f22c05ed33455ea7699403.js:22)
    at c.receiveComponent (cdn.wetransfer.net/assets/application-9a010fe19a400cdab6864b333504321f9460f3da30f22c05ed33455ea7699403.js:22)
    at Object.receiveComponent (cdn.wetransfer.net/assets/application-9a010fe19a400cdab6864b333504321f9460f3da30f22c05ed33455ea7699403.js:8)
/myscript/nightmare/wetransfer/node_modules/nightmare/lib/preload.js:7 Uncaught TypeError: Cannot read property 'stack' of null
    at /myscript/nightmare/wetransfer/node_modules/nightmare/lib/preload.js:7:59
`

If I do not 

` .click('div.transfer__footer button.transfer__button') `

I don't recive errors.
Some idea?

Thx!

**Comment by nlack** [comment]
try to make a javascript submit?
https://www.w3schools.com/jsref/met_form_submit.asp

**Comment by casesandberg** [comment]
I am going to close this, but feel free to open a new issue if you can't get it work.
