### ISSUE TITLE
Error: Could not start Xvfb

### ISSUE THREAD

**Issue by ScionOfBytes** [segmentio/nightmare#1167]
Okay, so this has been bugging me for a long time and I can't seem to find any literature around it. So let's start with my setup.

This is the code that runs Nightmare and Xvfb:

```js
const _scrape = function (url) {
  return co(function* () {

    const TIMEOUTS = 90000

    const xvfb = new Xvfb({ silent: true })
    xvfb.startSync()

    const nightmare = Nightmare({
      show: false,
      waitTimeout: TIMEOUTS,
      gotoTimeout: TIMEOUTS,
      loadTimeout: TIMEOUTS,
      executionTimeout: TIMEOUTS
    })

    try {

      const pageMeta = yield nightmare.goto(url)
      const headers = pageMeta.headers

      const env = yield nightmare.evaluate(() => Object.keys(window)) // eslint-disable-line no-undef
      const html = yield nightmare.evaluate(() => document.documentElement.outerHTML) // eslint-disable-line no-undef
      const canonicalUrl = yield nightmare.evaluate(() => window.location.href) // eslint-disable-line no-undef

      yield nightmare.end()
      xvfb.stopSync()

      return {
        url,
        canonicalUrl,
        html,
        headers,
        env
      }
    } catch (err) {

      nightmare.end()
      xvfb.stopSync()
      throw err
    }
  })()
}
```

This runs inside a docker container. The container is set up like so:

```
# take default image of node boron i.e  node 6.x
FROM node:boron

#create an app directory
RUN mkdir /app

COPY package.json /app

#make /app as the working directory
WORKDIR /app

# update the package manager, install git, add ssh_key from build argument and add it to the container.
# install all the prod dependency and remove the unnnecessary packages again to make the build size small.
RUN apt-get update

ENV BUILD_DEPS git
RUN apt-get -y install $BUILD_DEPS > /dev/null

ENV PROD_DEPS xvfb x11-xkb-utils xfonts-100dpi xfonts-75dpi xfonts-scalable xfonts-cyrillic x11-apps clang libdbus-1-dev libgtk2.0-dev libnotify-dev libgnome-keyring-dev libgconf2-dev libasound2-dev libcap-dev libcups2-dev libxtst-dev libxss1 libnss3-dev gcc-multilib g++-multilib
RUN apt-get -y install $PROD_DEPS > /dev/null

RUN npm config set registry http://registry.npmjs.org/ && \
    npm install --production > /dev/null
RUN apt-get -y remove $BUILD_DEPS > /dev/null && \
    apt-get -y autoremove  > /dev/null && \
    rm -rf /root/.ssh
COPY . /app/

CMD ["sh", "-c" ,"node_modules/knex/bin/cli.js migrate:latest && npm start"]
```

This server runs as a worker server and always processes one url at a time. But about 50% of them fail because of this error:

```
Error: Could not start Xvfb.
    at Object.startSync (/app/node_modules/xvfb/index.js:84:17)
    at /app/lib/scrappy/nightmareService/nightmare/index.js:108:10
    at next (native)
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/app/node_modules/bluebird/js/release/generators.js:97:49)
    at /app/node_modules/bluebird/js/release/generators.js:201:15
    at _scrape (/app/lib/scrappy/nightmareService/nightmare/index.js:143:5)
    at /app/lib/scrappy/nightmareService/nightmare/index.js:80:20
    at next (native)
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/app/node_modules/bluebird/js/release/generators.js:97:49)
    at /app/node_modules/bluebird/js/release/generators.js:201:15
    at _processUrl (/app/lib/scrappy/nightmareService/nightmare/index.js:95:5)
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/app/node_modules/bluebird/js/release/map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (/app/node_modules/bluebird/js/release/promise_array.js:113:31)
    at MappingPromiseArray.init (/app/node_modules/bluebird/js/release/promise_array.js:77:10)
    at MappingPromiseArray._asyncInit (/app/node_modules/bluebird/js/release/map.js:30:10)
    at Async._drainQueue (/app/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/app/node_modules/bluebird/js/release/async.js:17:14)
    at Immediate.wrapped (/app/node_modules/newrelic/lib/transaction/tracer/index.js:182:28)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```

Now for the life of me I can't figure out what's going wrong. And this never happens I'm testing!

**Comment by ian-axelrod** [comment]
I am getting the same error. Same exact line of code in xvfb/index.js.

**Comment by casesandberg** [comment]
Can you run the script with `DEBUG=*` and see what it returns?

**Comment by casesandberg** [comment]
I am going to close this, but feel free to open a new issue with some more details if it still doesnt work for you.
