### ISSUE TITLE
TypeError: key.charAt is not a function

### ISSUE THREAD

**Issue by rmartins90** [segmentio/nightmare#1179]
When using lodash cloneDeep function nightmare returns a TypeError.

```
TypeError: key.charAt is not a function
	    at Object.has (index.js:20439:50)
	    at baseGetTag (index.js:3900:48)
	    at baseClone (index.js:3485:19)
	    at index.js:3524:34
	    at arrayEach (index.js:1359:11)
	    at baseClone (index.js:3518:7)
	    at index.js:3524:34
	    at arrayEach (index.js:1359:11)
	    at baseClone (index.js:3518:7)
	    at Object.cloneDeep (index.js:11924:14)
```

**Comment by casesandberg** [comment]
Can you provide some more information or a code example? I am going to close this for now but feel free to open a new issue with some more details.
