### ISSUE TITLE
Error running example

### ISSUE THREAD

**Issue by matt-jarrett** [segmentio/nightmare#1231]
Machine info:
```
$ node -v
v8.4.0
$ npm -v
5.3.0
```

New project with `nightmare` and `eslint` installed.

I copied the example code from Nightmare's README:
```
var Nightmare = require('nightmare');		
var nightmare = Nightmare({ show: true });

nightmare
  .goto('https://duckduckgo.com')
  .type('#search_form_input_homepage', 'github nightmare')
  .click('#search_button_homepage')
  .wait('#zero_click_wrapper .c-info__title a')
  .evaluate(function () {
    return document.querySelector('#zero_click_wrapper .c-info__title a').href;
  })
  .end()
  .then(function (result) {
    console.log(result);
  })
  .catch(function (error) {
    console.error('Search failed:', error);
  });
```

The error I get after it can't seem to resolve the `wait`:
```
$ node index.js 
Search failed: Error: .wait() timed out after 30000msec
    at Timeout._onTimeout (/Users/cujarrett/Development/learning-nightmare-js/node_modules/nightmare/lib/actions.js:453:10)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
$ 
```

Any help? Seems to me the wait is looking for an element (maybe class) that can't be found on the README example.

**Comment by airtoxin** [comment]
README example dependent to duckduckgo.com's page structure.
Use `'#links_wrapper .result__title a'` selector instead of `'#zero_click_wrapper .c-info__title a'`.

**Comment by carbonsam** [comment]
I'm not able to get the example to work either - even with the new selectors. I'm getting a different error when the test fails though:

```javascript
Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  at pTimeout (node_modules/jest-jasmine2/build/queueRunner.js:53:21)
  at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
  at ontimeout (timers.js:380:14)
  at tryOnTimeout (timers.js:244:5)
  at Timer.listOnTimeout (timers.js:214:5)
```

Test I'm running is here:
```javascript
var Nightmare = require('nightmare');

describe('test duckduckgo search results', function() {
  it('should find the nightmare github link first', function(done) {
    var nightmare = Nightmare();

    nightmare
      .goto('https://duckduckgo.com')
      .type('#search_form_input_homepage', 'github nightmare')
      .click('#search_button_homepage')
      .wait('#links_wrapper .result__title a')
      .evaluate(function () {
        return document.querySelector('#links_wrapper .result__title a').href
      })
      .end()
      .then(function(link) {
        expect(link).to.equal('https://github.com/segmentio/nightmare');
        done();
      });
  });
});
```

Node version is `6.10.2` and I'm using Jest as my test framework. Running on the Windows 10 Ubuntu subsystem as well.

**Comment by k1r0s** [comment]
worked for me https://github.com/segmentio/nightmare/pull/1232

**Comment by matt-jarrett** [comment]
> Use '#links_wrapper .result__title a' selector instead of '#zero_click_wrapper .c-info__title a'.

Thanks!
