### ISSUE TITLE
installation fails on build server - failed to find Electron v1.8.0 for linux-x64

### ISSUE THREAD

**Issue by gmunisifreddy** [segmentio/nightmare#1269]
When we build one of the apps that uses nightmarejs on a linux CI server, i get the following. Any suggestions on how to solve the issue?

```
error /home/jenkins/workspace/xxx/node_modules/electron: Command failed.
Exit code: 1
Command: sh
Arguments: -c node install.js
Directory: /home/jenkins/workspace/monalisa/node_modules/electron
Output:
/home/jenkins/workspace/xxxx/node_modules/electron/install.js:48
  throw err
  ^

Error: Failed to find Electron v1.8.0 for linux-x64 at https://github.com/electron/electron/releases/download/v1.8.0/electron-v1.8.0-linux-x64.zip
    at Request.<anonymous> (/home/jenkins/workspace/xxxx/node_modules/nugget/index.js:169:61)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestResponse (/home/jenkins/workspace/xxx/node_modules/request/request.js:1068:10)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:473:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at TLSSocket.socketOnData (_http_client.js:362:20)
    at emitOne (events.js:96:13)
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
{ Error: Command failed: yarn add node-server@0.6.3 appmeta-register-ebay@4.0.1 --dev --no-progress --no-emoji --ignore-engines --pure-lockfile --cache-folder /home/jenkins/workspace/monalisa/.yarn-cache
```

**Comment by atkinchris** [comment]
This is due to Electron `v1.8.0` being deleted from GitHub, apparently due to a security vulnerability. (https://github.com/electron/electron/issues/10574#issuecomment-331373344)

Restricting Nightmare's dependency to an existing version would resolve this (or waiting till Electron publishes `v1.8.1` - but there's no ETA for this).

**Comment by atkinchris** [comment]
I've raised https://github.com/segmentio/nightmare/pull/1270 to pin the version of Electron to the latest stable (`v1.7.6`).

**Comment by matthewmueller** [comment]
Hey guys, it looks like the fix was merged in. If you're still running into problems, feel free to reopen!
