### ISSUE TITLE
.wait() timed out after 30000msec

### ISSUE THREAD

**Issue by zanedb** [segmentio/nightmare#1317]
I'm getting the following error when attempting to run `.wait(40000)`:

    Error: Error: .wait() timed out after 30000msec
    at Nightmare.<anonymous> (D:\code\nightmaretest\node_modules\nightmare\lib\actions.js:382:14)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)

This seems to indicate a timeout. Is this intentional or a bug?

**Comment by airtoxin** [comment]
Use `waitTimeout` parameter https://github.com/segmentio/nightmare#waittimeout-default-30s

**Comment by zanedb** [comment]
Thanks!
