### ISSUE TITLE
Cannot read property 'dock' of undefined in runner.js

### ISSUE THREAD

**Issue by kryptokinght** [segmentio/nightmare#1333]
I am trying to run nightmare on a windows system using windows powershell. But when i run it i get this error : 
`PS D:\web-scraping2> node app.js
Now checking HP431696
Nightmare runner error:

    TypeError: Cannot read property 'dock' of undefined
        at Object.<anonymous> (D:\web-scraping2\node_modules\nightmare\lib\runner.js:58:29)

        at Object.<anonymous> (D:\web-scraping2\node_modules\nightmare\lib\runner.js:652:3)
        at Module._compile (module.js:571:32)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:488:32)
        at tryModuleLoad (module.js:447:12)
        at Function.Module._load (module.js:439:3)
        at Module.runMain (module.js:605:10)
        at run (bootstrap_node.js:431:7)
        at startup (bootstrap_node.js:155:9)`
So i checked the runner.js file and i found this comment written just above line 58 : "app.dock is not defined when running electron in a platform other than OS X." I think this is the reason for the error. Since i am running a windows platform what can be the solution?
--

**Comment by kryptokinght** [comment]
The problem occurred because i was running electron from the terminal integrated in the Atom IDE.
