### ISSUE TITLE
ERR_NO_SUPPORTED_PROXIES when using proxies

### ISSUE THREAD

**Issue by mck457** [segmentio/nightmare#1354]
title

**Comment by matthewmueller** [comment]
Hi @mck457, can you provide an example that illustrates this problem?

**Comment by matthewmueller** [comment]
Going to close this since this issue is getting stale. Please feel free to reopen if you're still running into this problem and have additional information for us :-)

**Comment by benonymus** [comment]
Hey I am getting this error now, I am using the proxy example and this is the output i  am getting:
```
{ Error: navigation error
    at unserializeError (/home/holo/Projects/scraper2/node_modules/nightmare/lib/ipc.js:162:13)
    at EventEmitter.<anonymous> (/home/holo/Projects/scraper2/node_modules/nightmare/lib/ipc.js:89:13)
    at Object.onceWrapper (events.js:273:13)
    at EventEmitter.emit (events.js:182:13)
    at ChildProcess.<anonymous> (/home/holo/Projects/scraper2/node_modules/nightmare/lib/ipc.js:49:10)
    at ChildProcess.emit (events.js:182:13)
    at emit (internal/child_process.js:812:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  code: -336,
  details: 'ERR_NO_SUPPORTED_PROXIES',
  url: 'http://www.ipchicken.com/' }
```

**Comment by benonymus** [comment]
Hey I am getting this error now, I am using the proxy example and this is the output i  am getting:
{ Error: navigation error
    at unserializeError (/home/holo/Projects/scraper2/node_modules/nightmare/lib/ipc.js:162:13)
    at EventEmitter.<anonymous> (/home/holo/Projects/scraper2/node_modules/nightmare/lib/ipc.js:89:13)
    at Object.onceWrapper (events.js:273:13)
    at EventEmitter.emit (events.js:182:13)
    at ChildProcess.<anonymous> (/home/holo/Projects/scraper2/node_modules/nightmare/lib/ipc.js:49:10)
    at ChildProcess.emit (events.js:182:13)
    at emit (internal/child_process.js:812:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  code: -336,
  details: 'ERR_NO_SUPPORTED_PROXIES',
  url: 'http://www.ipchicken.com/' }
