### ISSUE TITLE
Error when using example in Electron application

### ISSUE THREAD

**Issue by jelmervisser** [segmentio/nightmare#1382]
When I try to use the example in my Electron application I get an error.

nightmare-example.js:
```
const Nightmare = require('nightmare')
const nightmare = Nightmare({ show: false })

nightmare
        .goto('https://duckduckgo.com')
        .type('#search_form_input_homepage', 'github nightmare')
        .click('#search_button_homepage')
        .wait('#r1-0 a.result__a')
        .end()
        .then(console.log)
        .catch(error => {
            console.error('Search failed:', error)
        })
```
Error:
```
Search failed: TypeError: "file" argument must be a non-empty string
    at normalizeSpawnArguments (child_process.js:392:11)
    at Object.exports.spawn (child_process.js:499:38)
    at Nightmare.queue (/node_modules/nightmare/lib/nightmare.js:123:22)
    at next (node_modules/nightmare/lib/nightmare.js:341:12)
    at Nightmare.run (/node_modules/nightmare/lib/nightmare.js:331:3)
    at /node_modules/nightmare/lib/nightmare.js:492:10
    at Promise (<anonymous>)
    at Nightmare.then (/node_modules/nightmare/lib/nightmare.js:490:10)
    at Object.scrape21 (webpack-internal:///29:6:167)
    at eval (webpack-internal:///5:7:10)
(anonymous) @ webpack-internal:///29:7
```
Can't I use nightmare in an existing Electron application or do I miss something?

**Comment by matthewmueller** [comment]
hi @jelmervisser, right now that's not possible, but we're tracking it in https://github.com/segmentio/nightmare/issues/393

In the meantime, you may want to try this PR: https://github.com/segmentio/nightmare/pull/967. I haven't tried it yet but it may accomplish your goal
