### ISSUE TITLE
Error: navigation error, code: -7

### ISSUE THREAD

**Issue by val7000** [segmentio/nightmare#1417]
Hi

This error sometimes appears. I can't figured out what is the reason. 
I noticed that it throws error before it it tries type into forms input.

It is cron log:

Fri, 16 Mar 2018 06:20:02 GMT nightmare queuing process start
Fri, 16 Mar 2018 06:20:02 GMT nightmare queueing action "viewport"
Fri, 16 Mar 2018 06:20:02 GMT nightmare queueing action "goto" for https://example.com/sign
Fri, 16 Mar 2018 06:20:02 GMT nightmare queueing action "wait"
Fri, 16 Mar 2018 06:20:02 GMT nightmare queueing action "type"
Fri, 16 Mar 2018 06:20:02 GMT nightmare queueing action "type"
Fri, 16 Mar 2018 06:20:02 GMT nightmare queueing action "click"
Fri, 16 Mar 2018 06:20:02 GMT nightmare queueing action "wait"
Fri, 16 Mar 2018 06:20:02 GMT nightmare queueing action "wait"
Fri, 16 Mar 2018 06:20:02 GMT nightmare queueing action "goto" for https://example.com/test.html
Fri, 16 Mar 2018 06:20:02 GMT nightmare queueing action "wait"
Fri, 16 Mar 2018 06:20:02 GMT nightmare queueing action "click"
Fri, 16 Mar 2018 06:20:02 GMT nightmare queueing action "wait"
Fri, 16 Mar 2018 06:20:02 GMT nightmare queueing action "evaluate"
Fri, 16 Mar 2018 06:20:02 GMT nightmare running
Fri, 16 Mar 2018 06:20:38 GMT nightmare queueing action "title"
Fri, 16 Mar 2018 06:20:38 GMT nightmare running
{ Error: navigation error
    at unserializeError (/var/www/nightmare/node_modules/nightmare/lib/ipc.js:162:13)
    at EventEmitter.<anonymous> (/var/www/nightmare/node_modules/nightmare/lib/ipc.js:89:13)
    at Object.onceWrapper (events.js:293:19)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:194:7)
    at ChildProcess.<anonymous> (/var/www/nightmare/node_modules/nightmare/lib/ipc.js:49:10)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at process.nextTick (internal/child_process.js:766:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
  code: -7,
  details: 'Navigation timed out after 30000 ms',
  url: 'https://example.com/sign' }

Thanks

**Comment by KonyDev** [comment]
Were you able to resolve it ?

**Comment by val7000** [comment]
@KonyDev Unfortunately, no. Still wait for author's response.

**Comment by edoardoo** [comment]
Is there any additional data we can provide to help fixing this?

**Comment by mh4ck** [comment]
Got the same error on a raspberry pi - are there any fixes?
