### ISSUE TITLE
Reference error evaluating document

### ISSUE THREAD

**Issue by JereMc** [segmentio/nightmare#1425]
I tried the call this way:
let nightmare = Nightmare({ show: false});
  (async () => {
    try {
      const doc = await nightmare
        .goto(url)
        .evaluate(() => {
          return document.documentElement.innerHTML;
        })
        .end();
      return doc;
    } catch(e) {
      console.error(e);
      return undefined;
    }
  })();

and this way:
let nightmare = Nightmare({ show: false});
  nightmare
    .goto(url)
    .evaluate(() => {
      return document.documentElement.innerHTML;
    })
    .end()
    .then(doc => {
      return doc;
    })
    .catch(function(err) {
      console.log(err);
      return null;
    });

and with both I get:

{ ReferenceError: cov_eneajp1f5 is not defined
    at fn (<anonymous>:6:5)
    at javascript (<anonymous>:24:21)
    at <anonymous>:39:3
    at EventEmitter.electron.ipcRenderer.on (/Users/jeremiahmcallister/Developer/Desirelist/desirelist-api/application/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/init.js:63:28)
    at emitMany (events.js:146:13)
    at EventEmitter.emit (events.js:223:7) code: -1 }

Any ideas why?

**Comment by eddiewang** [comment]
@JereMc did you ever manage to figure out the root cause of this issue?
