### ISSUE TITLE
Packing with webpack results in Error: Cannot find module "/package.json"

### ISSUE THREAD

**Issue by nukeop** [segmentio/nightmare#1455]
Stack trace:

```
undefined:4
        throw e;
        ^

Error: Cannot find module "/package.json".
    at webpackEmptyContext (eval at ./node_modules/nightmare/lib sync recursive (<project dir>/dist/worker.js:1683:1), <anonymous>:2:10)
    at Object.eval (webpack-internal:///./node_modules/nightmare/lib/nightmare.js:278:87)
    at eval (webpack-internal:///./node_modules/nightmare/lib/nightmare.js:587:30)
    at Object../node_modules/nightmare/lib/nightmare.js (<project dir>/dist/worker.js:1728:1)
    at __webpack_require__ (<project dir>/dist/worker.js:20:30)
    at eval (webpack-internal:///./src/worker/index.js:7:18)
    at Object../src/worker/index.js (<project dir>/dist/worker.js:2061:1)
    at __webpack_require__ (<project dir>/dist/worker.js:20:30)
    at <project dir>/dist/worker.js:69:18
    at Object.<anonymous> (<project dir>/dist/worker.js:72:10)

```

I'm packing a fairly mundane script (one goto, one click, one pdf command) with webpack using target: 'electron-main' using no unusual settings. It packs without problems, then trying to run it results in the above stack trace. Any idea what's going on or should I include more details?

**Comment by nukeop** [comment]
Examining the bundle shows there's this bit of code responsible for this:

```
Nightmare.childActions = {};\n\n/**\n * Version\n */\nNightmare.version = __webpack_require__(\"./node_modules/nightmare/lib sync recursive\")(path.resolve(__dirname, '..', 'package.json')).version;
```

**Comment by nukeop** [comment]
Several hours later: turns out that webpack replaces __dirname with '/' by default. You have to use an option to use the true value, which is documented here: https://webpack.js.org/configuration/node/

**Comment by rzfzr** [comment]
No luck with my project, adding __dirname: false inside configureWebpack, a vue project, any ideas?
```
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property '__dirname'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry?, externals?, infrastructureLogging?, loader?, mode?, module?, name?, node?, optimization?, output?, parallelism?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, serve?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack >= v2.0.0 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: [
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           __dirname: …
         }
       })
     ]
    at webpack (C:\Users\capit\Desktop\GitGud\CNVU\node_modules\webpack\lib\webpack.js:31:9)
    at serve (C:\Users\capit\Desktop\GitGud\CNVU\node_modules\@vue\cli-service\lib\commands\serve.js:163:22)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async C:\Users\capit\Desktop\GitGud\CNVU\node_modules\vue-cli-plugin-electron-builder\index.js:291:22
```

**Comment by hairedfox** [comment]
@rzfzr I have the same issue right now :( do you find any solution yet?
I'm trying to use Nightmare with my Vue-Electron app

**Comment by hairedfox** [comment]
@rzfzr If you're still looking for a solution for this. Here's the thing that I've just tried and it worked :D

```js
// vue.config.js

module.exports = {
  pluginOptions: {
    electronBuilder: {
      nodeIntegration: true,
      externals: ['nightmare']
    }
  }
}
```

I've been struggled with this issue all night. But it works now :D

**Comment by rzfzr** [comment]
Thanks for the followup, will check it out whenever I come back to using nightmare, for the project I was working on, I'm now using the official API for the service.
