### ISSUE TITLE
Nightmare compatibility with Phantomjs 2.0.0

### ISSUE THREAD

**Issue by edasque** [segmentio/nightmare#150]
Once I updated to Phanthomjs 2.0.0 my application using nightmare stopped working, probably related:

```
/Users/bob/projects/nightnight/node_modules/nightmare/node_modules/phantom/node_modules/dnode/node_modules/weak/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/Users/bob/projects/nightnight/node_modules/nightmare/node_modules/phantom/node_modules/dnode/node_modules/weak/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/bob/projects/nightnight/node_modules/nightmare/node_modules/phantom/node_modules/dnode/node_modules/weak/lib/weak.js:7:35)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

**Comment by edasque** [comment]
Was linked an OS update, I think
