### ISSUE TITLE
control-c the node process doesn't kill the phantomjs processes

### ISSUE THREAD

**Issue by izelnakri** [segmentio/nightmare#152]
control-c the node process doesn't kill the phantomjs process and sometimes randomly but frequently I get this error:

phantom stderr: PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/D3087DE3-8A3E-43B8-88FE-64E7809F4C2B.dmp

assert.js:100
  throw new assert.AssertionError({
        ^
AssertionError: abnormal phantomjs exit code: 1
  at Console.assert (console.js:87:23)
  at ChildProcess.<anonymous> (/Users/izelnakri/newkamernet/node_modules/nightmare/node_modules/phantom/phantom.js:153:28)
  at ChildProcess.emit (events.js:101:17)
  at Process.ChildProcess._handle.onexit (child_process.js:1038:12)

**Comment by reinpk** [comment]
yeah, definitely yucky — in v2 #200 we're moving to electron replacing phantomjs which should help
