### ISSUE TITLE
issue with proxy - 'ERR_NO_SUPPORTED_PROXIES'

### ISSUE THREAD

**Issue by benonymus** [segmentio/nightmare#1521]
Hey when I am trying to run the example with my proxy, I am getting this error.
this is the output: 

`{ Error: navigation error
    at unserializeError (/home/holo/Projects/scraper2/node_modules/nightmare/lib/ipc.js:162:13)
    at EventEmitter.<anonymous> (/home/holo/Projects/scraper2/node_modules/nightmare/lib/ipc.js:89:13)
    at Object.onceWrapper (events.js:273:13)
    at EventEmitter.emit (events.js:182:13)
    at ChildProcess.<anonymous> (/home/holo/Projects/scraper2/node_modules/nightmare/lib/ipc.js:49:10)
    at ChildProcess.emit (events.js:182:13)
    at emit (internal/child_process.js:812:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  code: -336,
  details: 'ERR_NO_SUPPORTED_PROXIES',
  url: 'http://www.ipchicken.com/' }
`

**Comment by benonymus** [comment]
probabaly an issue with the proxy
