### ISSUE TITLE
Tests are crashing when i change the base url.

### ISSUE THREAD

**Issue by yoihito** [segmentio/nightmare#227]
I was trying to setup e2e test environment with nightmare and mocha. I get stucked with example from readme. Then I tried to run nightmare standard test against my application and got this stack trace.

OS: Ubuntu 14.04
Node: 4.0.0

``` 
 Nightmare
    ✓ should be constructable
    navigation
      1) should click on a link and then go back
      2) should work for links that dont go anywhere
      3) should click on a link, go back, and then go forward
      4) should refresh the page
      5) "after each" hook
Error: IPC channel is already disconnected
    at ChildProcess.target.disconnect (internal/child_process.js:630:26)
    at Nightmare.done (lib/nightmare.js:158:17)
    at Nightmare.next (lib/nightmare.js:140:28)
    at EventEmitter.<anonymous> (lib/nightmare.js:150:12)
    at ChildProcess.<anonymous> (lib/ipc.js:28:10)
    at handleMessage (internal/child_process.js:685:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: IPC channel is already disconnected
    at ChildProcess.target.disconnect (internal/child_process.js:630:26)
    at process.<anonymous> (/home/yoihito/Work/expedite/ls-portal/node_modules/nightmare/lib/nightmare.js:58:15)
    at emitOne (events.js:82:20)
    at process.emit (events.js:169:7)
    at process._fatalException (node.js:211:26)
```

**Comment by matthewmueller** [comment]
Hm... that error is usually the result of another error crashing the process. Was there any more errors associated with it? We could use some more error output to diagnose

**Comment by yoihito** [comment]
How can I get electron errors log?

**Comment by reinpk** [comment]
added docs here: https://github.com/segmentio/nightmare#debugging
