### ISSUE TITLE
How to provide options to "pdf" ?

### ISSUE THREAD

**Issue by ocombe** [segmentio/nightmare#264]
Hello !
The documentation states the following:
> .pdf(path, options)

>Saves a PDF with A4 size pages of the current page to the specified path. Options are here.

I tried this `.pdf('test.pdf', {printBackground: true})` and got the following error:
```sh
TypeError: object is not a function
    at EventEmitter.<anonymous> (C:\www\holimetrix\expooort\renderer\node_modules\Nightmare\lib\actions.js:431:5)
    at EventEmitter.g (events.js:199:16)
    at EventEmitter.emit (events.js:107:17)
    at ChildProcess.<anonymous> (C:\www\holimetrix\expooort\renderer\node_modules\Nightmare\lib\ipc.js:28:10)
    at ChildProcess.emit (events.js:110:17)
    at handleMessage (child_process.js:324:10)
    at Pipe.channel.onread (child_process.js:352:11)
```

If I just render to pdf without options it works fine. I checked the tests but you never use any option with the pdf method... :(

So, how can I provide options to `pdf` ?

**Comment by ocombe** [comment]
Just did a PR to fix this :)
