### ISSUE TITLE
.evaluate doesn't provide current open page's document variable

### ISSUE THREAD

**Issue by DWboutin** [segmentio/nightmare#333]
Hi, i'm trying to get the document's scrollWidth and scrollHeight with evaluate, but it do nothing. I want to pass my pageWidth and pageHeight to the screenshot method. How can i do this?

```javascript
var pageWidth;
var pageHeight;
var nightmare = new Nightmare();
var nightmare = new Nightmare();
var NRdashboard = nightmare
    .viewport(1920, 1080)
    .useragent('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.93 Safari/537.36')
    .goto('https://login.newrelic.com/login')
    .wait()
    .type('#login_email', '***')
    .type('#login_password', '***')
    .click('#login_submit')
    .wait('body')
    .evaluate(function() {
        console.log('ASS');  // doesn't log
        console.log(document); // doesn't log
        pageWidth = document.body.scrollWidth;
        pageHeight = document.body.scrollHeight;
        return document.body.scrollWidth; // contains nothing
    })
    .screenshot(content_dir + '/dashboard.png')
    .goto('https://insights.newrelic.com/accounts/123456/dashboards/12345?kiosk=true')
    .wait(2000)
    .screenshot(content_dir + '/dashboard2.png')
    .run(function (err, nightmare) {
        if (err) return console.log(err);
        console.log('Done!');
        console.log(pageWidth, pageHeight); // undefined, undefined
    })
    .end();
```

**Comment by fmaruki** [comment]
Variables inside the evaluate are in a different context than the functions from outside, so a variable won't be passed automatically. You need to pass variables from outside as the extra arguments of evaluate, and pass values back with return.
```javascript
 var dimensions = yield nightmare.viewport(x, y) ... .evaluate(function() {
     ... ;
     return {pageWidth: pageWidth, pageHeight: pageHeight}
 }, arg1, arg2);
 var pageWidth = dimensions.pageWidth;
```

**Comment by DWboutin** [comment]
But how can i access do the document object?

**Comment by DWboutin** [comment]
I tried to set things like you and the yield keyword. But it won't work.

```javascript
function* newRelicDashboard(){

  var pageWidth;
  var pageHeight;

  var nightmare = Nightmare();

  yield nightmare
    .viewport(1920, 1080)
    .useragent('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.93 Safari/537.36')
    .goto('https://login.newrelic.com/login')
    .wait()
    .type('#login_email', '***')
    .type('#login_password', '***')
    .click('#login_submit')
    .wait()
    .goto('https://insights.newrelic.com/accounts/123456/dashboards/12345?kiosk=true')
    .wait(2000);

  var pageWidth = yield nightmare
    .evaluate(function (selector) {
      // now we're executing inside the browser scope.
      return document.body.scrollWidth;
    });

  var pageHeight = yield nightmare
    .evaluate(function (selector) {
      // now we're executing inside the browser scope.
      console.log(document.body.scrollHeight);
      return document.body.scrollHeight;
    });

  yield nightmare
    .evaluate(function(){
      localStorage.setItem('kioskNoir', 'true');
    })
    .screenshot(content_dir + '/dashboard2.png')
    .run(function (err, nightmare) {
      if (err) return console.log(err);
      console.log('Done!');
      console.log(pageWidth, pageHeight);  // undefined, undefined
    })
    .end();
}
```

**Comment by fmaruki** [comment]
You need to wrap the generator function in a call with the libraries/functions vo or co, and start node with the flag --harmony (don't need flags for io.js).
Sorry for using yield, maybe it is not mandatory, I just never used nightmare without it.

**Comment by DWboutin** [comment]
It's ok! I tried this but it gaves me errors in Electron. The `dimensions` is ok now, but when i try to screenshot Electron popup.

My script:
```javascript
var dimensions = yield nightmare
      .viewport(1920, 1080)
      .useragent('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.93 Safari/537.36')
      .goto('https://login.newrelic.com/login')
      .wait()
      .type('#login_email', '***')
      .type('#login_password', '***')
      .click('#login_submit')
      .goto('https://insights.newrelic.com/accounts/123456/dashboards/12345?kiosk=true')
      .wait(3000)
      .evaluate(function(){
        localStorage.setItem('kioskNoir', 'true');
      })
      .wait()
      .evaluate(function(){
        return {pageWidth: document.body.scrollWidth, pageHeight: document.body.scrollHeight};
      });

    var pageWidth = dimensions.pageWidth;
    var pageHeight = dimensions.pageHeight;

    yield nightmare
      .screenshot(content_dir + '/dashboard2.png', {
        rect: {
          width: pageWidth,
          height: pageHeight
        }
      })
      .end();
```

The Electron error:

```
Uncaught Exception:
TypeError: Error processing argument -1.
    at TypeError (native)
    at EventEmitter.<anonymous> (/Users/mboutin2/Desktop/tv/node_modules/nightmare/lib/runner.js:145:21)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at process.<anonymous> (/Users/mboutin2/Desktop/tv/node_modules/nightmare/lib/ipc.js:28:10)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:685:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)
```

**Comment by fmaruki** [comment]
I'm happy that you made it work!

Yield is like a return that can continue after the asynchronous operation is done. There must be someone wrapping the function to call it again as a callback once the result is set, so it can continue execution.

I usually use Co for this job, a library that I learned while programming with Koa.js. Vo looks like an sophisticated alternative to Co, I still don't know what it can do better for me.

Asynchronous callbacks, promisses, thunks and generators are all intimately related. It is a complex and fun topic, that I am still trying to fully understand.

Interesting links, I was trying to find another one, but can remember where it is:
https://www.promisejs.org/generators/
http://colintoh.com/blog/staying-sane-with-asynchronous-programming-promises-and-generators
https://medium.com/@rdsubhas/es6-from-callbacks-to-promises-to-generators-87f1c0cd8f2e

**Comment by DWboutin** [comment]
Thank you!

**Comment by rosshinkley** [comment]
It looks like this issue is resolved.  Closing.
