### ISSUE TITLE
Handle no callback argument in nightware.run()

### ISSUE THREAD

**Issue by h2non** [segmentio/nightmare#500]
I'm getting the following exception using `nightware@2.2.0`. Everytime I'm calling `.end(cb)` I'm passing a `function`, so I can't realize the nature of the issue from API consumer point of view.

``` js
TypeError: Cannot read property 'apply' of undefined
    at Nightmare.done (/Users/h2non/Projects/nightmare-google-oauth2/node_modules/nightmare/lib/nightmare.js:225:14)
    at Nightmare.next (/Users/h2non/Projects/nightmare-google-oauth2/node_modules/nightmare/lib/nightmare.js:202:35)
    at EventEmitter.<anonymous> (/Users/h2non/Projects/nightmare-google-oauth2/node_modules/nightmare/lib/nightmare.js:212:12)
    at EventEmitter.g (events.js:273:16)
    at emitNone (events.js:85:20)
    at EventEmitter.emit (events.js:179:7)
    at ChildProcess.<anonymous> (/Users/h2non/Projects/nightmare-google-oauth2/node_modules/nightmare/lib/ipc.js:28:10)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at handleMessage (internal/child_process.js:695:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)
```

**Comment by casesandberg** [comment]
Are you still having trouble and have you tried 2.10.0? I am going to close this, but feel free to re-open if it's still an issue.
