### ISSUE TITLE
Catching "Nightmare runner error"

### ISSUE THREAD

**Issue by yoz** [segmentio/nightmare#558]
Occasionally because of bugs in Electron such as https://github.com/electron/electron/issues/4733 I run into errors that look like the following:

`Nightmare runner error:`
`TypeError: Cannot read property 'delete' of undefined at ObjectsRegistry.remove (/app/node_modules/electron-prebuilt/dist/resources/electron.asar/browser/objects-registry.js:53:31) at EventEmitter.<anonymous> (/app/node_modules/electron-prebuilt/dist/resources/electron.asar/browser/rpc-server.js:344:26) at emitTwo (events.js:100:13) at EventEmitter.emit (events.js:185:7) at EventEmitter.<anonymous> (/app/node_modules/electron-prebuilt/dist/resources/electron.asar/browser/api/web-contents.js:128:25) at emitTwo (events.js:100:13) at EventEmitter.emit (events.js:185:7)`

These seem to hang Nightmare - they log an error to the console and end the child process. However, I'd like to be able to catch such errors in my code that is using Nightmare. Is there a good way to do this?

**Comment by rosshinkley** [comment]
How are you getting these errors?  Are you using custom plugins?

By the time the exception makes it to the `uncaughtException` handler, it's too late.  I don't think you're inside of the Nightmare chain scope anymore, and as such couldn't handle it in such a way to continue execution.

**Comment by yoz** [comment]
I am using custom actions I've defined, but I'm fairly confident it was due to the bug in Electron that I linked. (If "delete" is confusing to you, it is confusing to me too, because my custom action doesn't involve deletion; it is basically like `nightmare.insert(''); nightmare.insert(x);`)

I see that in Nightmare's handler there's a call to `process.exit(1)` when this happens - what if I don't want to end the parent process?

**Comment by Mr0grog** [comment]
> I see that in Nightmare's handler there's a call to process.exit(1) when this happens - what if I don't want to end the parent process?

So… it would be a *very* bad idea not to exit the process at this point. Electron’s underlying IPC machinery is now in a bad state, so further communication between the your node.js process and the “browser” is not reliable. Worse, the underlying issue is a memory management problem on the C++ side, which means you are prone to crashing if you keep running.

If indeed https://github.com/electron/electron/issues/4733 is the problem, it’s been fixed. When Nightmare next updates its Electron dependency, this should be solved. (You can update the version of Electron you’re using yourself, too. The current release should have the fix for this issue.)

**Comment by yoz** [comment]
https://github.com/electron/electron/issues/4733 was reopened, so I think that's still the underlying bug I'm trying to handle.

**Comment by Mr0grog** [comment]
@yoz ah, that’s frustrating. It sounds like the issues in Electron are fairly thorny.

I get wanting to be able to continue on after Nightmare fails, but I’m pretty sure Nightmare really does not handle the underlying Electron process failing very gracefully. A lot more would need to be done to fix that if you want it to be safe to not just exit the process when Electron fails. It would probably be a good improvement if you want to work on it, though!

**Comment by yoz** [comment]
@Mr0grog yes, unfortunately it's a pretty difficult bug to reproduce. I would look into it if I had an easier time with that. But I think the easiest for me is to downgrade my version of electron-prebuilt to 0.36.8.

**Comment by bahlo** [comment]
:+1:

**Comment by rosshinkley** [comment]
@yoz electron/electron#4733 was fixed/reclosed in electron/electron#5233, which should be in the release of `electron-prebuilt` Nightmare is on as of 2.3.4.  Can you upgrade and see if this issue still exists?

**Comment by rosshinkley** [comment]
Closing due to inactivity.  If this is still an issue, feel free to reopen/open a new issue.

**Comment by GautierT** [comment]
Hi !
How can i catch the 
```
Nightmare runner error:

	Error: Object has been destroyed
	    at Error (native)
	    at Timeout.wait [as _onTimeout] (eval at <anonymous> (/Users/gautier/Documents/Projets/lifebox/server/node_modules/nightmare/lib/runner.js:543:14), <anonymous>:89:35)
	    at tryOnTimeout (timers.js:232:11)
	    at Timer.listOnTimeout (timers.js:202:5)
```
To log it?

I'm on nightmare 2.10.0 / electron 1.4.4.
It's happening since 2-3 days after executing a script when i don't end nightmare and i let the window open. Very weird...
At least i would like to be able to send the error to sentry.
Thanks

**Comment by Kinzi** [comment]
+1

**Comment by rosshinkley** [comment]
@GautierT I think this is in reference to rosshinkley/nightmare-download-manager#14, picking up this conversation there.
