### ISSUE TITLE
yahoo.js example not working (yield unexpected identifier)

### ISSUE THREAD

**Issue by mingsterism** [segmentio/nightmare#605]
I'm running the example yahoo.js code locally on windows 8 with electron and node v6.0.0  installed locally. 
iI'ved tried both `node yahoo.js` and  `node --harmony yahoo.js`  but i get this error message. 
```
C:\Users\ming_o01\nightmarejs\electron-quick-start\nightmare1\yahoo.js:5
    var link = yield nightmare
                     ^^^^^^^^^
SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:53:16) 
    at Module._compile (module.js:511:25) 
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:159:18)
    at node.js:444:3
```

this is the actual code. 
```
var Nightmare = require('nightmare');
var nightmare = Nightmare({ show: true })

var nightmare = Nightmare()
    var link = yield nightmare
      .goto('http://yahoo.com')
      .type('input[title="Search"]', 'github nightmare')
      .click('#UHSearchWeb')
      .wait('#main')
      .evaluate(function () {
    return document.querySelector('#main .searchCenterMiddle li a').href
  })
  .end()
  .then(function (result) {
    console.log(result)
  })
```

Thanks very much.

**Comment by rosshinkley** [comment]
You're using `yield` outside of a generator, and I don't think that's legal.

Also, in your case, you don't need `yield` if you are using `.then()`.  At first glance, your source would probably work as expected if `yield` is removed.

**Comment by mingsterism** [comment]
@rosshinkley Thanks for the clarification.
