### ISSUE TITLE
Upgrading from 2.1 to 2.3 breaks the library in node 0.12

### ISSUE THREAD

**Issue by mathisonian** [segmentio/nightmare#620]
With the following error:

```

/Users/mathisonian/projects/.../node_modules/nightmare/lib/nightmare.js:75
  this.proc.stdout.pipe(split2()).on('data', (data) => {
                                                    ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous>
```

Is this expected / documented anywhere?

**Comment by rosshinkley** [comment]
Are you running with `--harmony`?  I _thought_ fat-arrow notation was supported (with some caveats with respect to binding `this`) in Node 0.12.x.  Open to being wrong, though.

Node 4.x+ is recommended for Nightmare, but I see now that it's not listed as the engine in `package.json`.  (I also know that assertion had been made before, but it's not jumping out at me where.)

**Comment by mathisonian** [comment]
Ah no, I wasn't running with `--harmony`. Not a huge deal, but I ran into the error when I depended on `^2.1.0` and got the semantic upgrade. 

Thanks for the response!

**Comment by rosshinkley** [comment]
I believe this issue has been resolved, closing.  If you continue to have problems, feel free to reopen/open a new issue.

**Comment by dcshapiro** [comment]
i have this issue.

**Comment by dcshapiro** [comment]
root@ubuntu-2gb-tor1-01:/images# node --harmony e.js

/images/node_modules/google-images-scraper/node_modules/nightmare/lib/nightmare.js:94
  this.queue((done) => {
                     ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/images/node_modules/google-images-scraper/lib/google-images-scraper.js:6:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/images/node_modules/google-images-scraper/index.js:1:80)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

**Comment by rosshinkley** [comment]
@dcshapiro What version of node and nightmare?

**Comment by dcshapiro** [comment]
root@ubuntu-2gb-tor1-01:~# nodejs --version
v0.10.25

and 

{
  "name": "nightmare",
  "version": "2.5.2",
  "license": "MIT",
  "main": "lib/nightmare.js",
  "scripts": {
    "test": "make test"

**Comment by rosshinkley** [comment]
@dcshapiro [Nightmare requires 4.x or higher.](https://github.com/segmentio/nightmare#node-versions)  See also #621.

I _think_ you might still be able to get away with using 0.12.x and `--harmony`, but your mileage may vary.
