### ISSUE TITLE
Why is this .evaluate() not working

### ISSUE THREAD

**Issue by ivawzh** [segmentio/nightmare#627]
I am trying to update the package `x-ray-phantom` from using old nightmare phantom driver to using electron. Fork here https://github.com/ivawzh/x-ray-phantom

However, `.evaluate()` seems not being triggered. 

```
return function electron_driver(ctx, done) {
    debug('going to %s', ctx.url)

    nightmare
      .on('unresponsive', function() {
        console.warn('the web page ' + ctx.url + 'becomes unresponsive.')
      })
      .on('responsive', function() {
        console.log('the unresponsive web page ' + ctx.url + 'becomes responsive again.')
      })
      .on('did-fail-load', function(event, errorCode, errorDescription) {
        console.error('nightmare did-fail-load error: ' + errorCode + '; ' + errorDescription)
        return new Error(errorDescription, errorCode)
      })
      .on('did-get-response-details', function(event, status, newUrl, originalUrl, httpResponseCode, requestMethod, referrer, headers) {
        if (normalize(originalUrl) == normalize(ctx.url)) {
          debug('got response from original url: %s, actual url: %s, httpResponseCode: %s', originalUrl, newUrl, httpResponseCode)
          ctx.status = httpResponseCode
        }
      })
      .on('dom-ready', function() {
        debug('dom-ready for %s', ctx.url)
      })
      .on('will-navigate', function(event, url) {
        debug('redirect: %s', url)
        ctx.url = url
      })

    wrapfn(fn, select)(ctx, nightmare)

    function select(err, ret) {
      if (err) done(err)
      console.log(11111)
      nightmare
        .evaluate(function() {
          console.log(22222)
          return document.documentElement.outerHTML
        }, function(body) {
          console.log(33333)
          ctx.body = body
        })
        .run(function(err) {
          console.log(44444)
          if (err) return done(err)
          debug('nightmare .run url: %s ; status: %s', ctx.url, ctx.status)
          done(null, ctx)
        })
    }
  }
```

Result from running `npm test`:
```
electron driver
  x-ray:electron going to http://google.com +5m
  x-ray:electron got response from original url: http://google.com/, actual url: https://www.google.com.au/?gfe_rd=cr&ei=NBQvV4TeJanM8gfioZnYCw&gws_rd=ssl, httpResponseCode: 200 +1s
  x-ray:electron dom-ready for http://google.com +246ms
11111
44444
  x-ray:electron nightmare .run url: http://google.com ; status: 200 +67ms
ctx:
context {
  response: { status: 200, message: 'OK', header: {}, body: null },
  request: { method: null, url: 'http://google.com', header: {} } }
    1) should have sensible defaults


  0 passing (2s)
  1 failing

  1) electron driver should have sensible defaults:
     Uncaught TypeError: Cannot read property 'parent' of null
      at Function.exports.update (node_modules/cheerio/lib/parse.js:55:25)
      at module.exports (node_modules/cheerio/lib/parse.js:17:11)
      at Function.exports.load (node_modules/cheerio/lib/static.js:19:14)
      at test/phantom.js:26:23
```

**Comment by rosshinkley** [comment]
First, the immediate problem: the way you're using `.evaluate()`, the function that accepts the body and sets `ctx.body` will be passed as an argument to the first function in `.evaluate()`.  Off the cuff, I think you want something like:

```js
      nightmare
        .evaluate(function() {
          return document.documentElement.outerHTML
        })
        .run(function(err, body) {
          ctx.body = body;
          if (err) return done(err)
          debug('nightmare .run url: %s ; status: %s', ctx.url, ctx.status)
          done(null, ctx)
        })
```

Second, a question for you: have you seen the [Nightmare driver for x-ray](https://github.com/phulas/x-ray-nightmare)?  Would that work for your application?

**Comment by ivawzh** [comment]
@rosshinkley Thanks for the answer. Your fork looks awesome, just one thing I cannot get pagination works. Is there anything special I need to config?
