### ISSUE TITLE
Error: Cannot find module 'sliced'

### ISSUE THREAD

**Issue by rrva** [segmentio/nightmare#752]
Using nightmare 2.6.0, electron seems to load nightmare but then stops running. Can provide Dockerfile which reproduces it fully.

```
Mon, 08 Aug 2016 09:39:16 GMT nightmare queuing process start
Mon, 08 Aug 2016 09:39:16 GMT nightmare queueing action "viewport"
Mon, 08 Aug 2016 09:39:16 GMT nightmare queueing action "useragent"
Mon, 08 Aug 2016 09:39:16 GMT nightmare queueing action "goto" for https://www.example.com
Mon, 08 Aug 2016 09:39:16 GMT nightmare queueing action "wait"
Mon, 08 Aug 2016 09:39:16 GMT nightmare queueing action "evaluate"
Mon, 08 Aug 2016 09:39:16 GMT nightmare running
Mon, 08 Aug 2016 09:39:16 GMT electron:stderr Xlib:  extension "RANDR" missing on display ":99".
Mon, 08 Aug 2016 09:39:16 GMT electron:stderr App threw an error during load
Mon, 08 Aug 2016 09:39:16 GMT electron:stderr Error: Cannot find module 'sliced'
Mon, 08 Aug 2016 09:39:16 GMT electron:stderr     at Module._resolveFilename (module.js:440:15)
Mon, 08 Aug 2016 09:39:16 GMT electron:stderr     at Function.Module._resolveFilename (/node_modules/electron-prebuilt/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
Mon, 08 Aug 2016 09:39:16 GMT electron:stderr     at Function.Module._load (module.js:388:25)
Mon, 08 Aug 2016 09:39:16 GMT electron:stderr     at Module.require (module.js:468:17)
Mon, 08 Aug 2016 09:39:16 GMT electron:stderr     at require (internal/module.js:20:19)
Mon, 08 Aug 2016 09:39:16 GMT electron:stderr     at Object.<anonymous> (/node_modules/nightmare/lib/ipc.js:8:14)
Mon, 08 Aug 2016 09:39:16 GMT electron:stderr     at Module._compile (module.js:541:32)
Mon, 08 Aug 2016 09:39:16 GMT electron:stderr     at Object.Module._extensions..js (module.js:550:10)
Mon, 08 Aug 2016 09:39:16 GMT electron:stderr     at Module.load (module.js:458:32)
Mon, 08 Aug 2016 09:39:16 GMT electron:stderr     at tryModuleLoad (module.js:417:12)
Mon, 08 Aug 2016 09:39:16 GMT electron:stderr A JavaScript error occurred in the main process
Mon, 08 Aug 2016 09:39:16 GMT electron:stderr Uncaught Exception:
Mon, 08 Aug 2016 09:39:16 GMT electron:stderr Error: Cannot find module 'sliced'
Mon, 08 Aug 2016 09:39:16 GMT electron:stderr     at Module._resolveFilename (module.js:440:15)
Mon, 08 Aug 2016 09:39:16 GMT electron:stderr     at Function.Module._resolveFilename (/node_modules/electron-prebuilt/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
Mon, 08 Aug 2016 09:39:16 GMT electron:stderr     at Function.Module._load (module.js:388:25)
Mon, 08 Aug 2016 09:39:16 GMT electron:stderr     at Module.require (module.js:468:17)
Mon, 08 Aug 2016 09:39:16 GMT electron:stderr     at require (internal/module.js:20:19)
Mon, 08 Aug 2016 09:39:16 GMT electron:stderr     at Object.<anonymous> (/node_modules/nightmare/lib/ipc.js:8:14)
Mon, 08 Aug 2016 09:39:16 GMT electron:stderr     at Module._compile (module.js:541:32)
Mon, 08 Aug 2016 09:39:16 GMT electron:stderr     at Object.Module._extensions..js (module.js:550:10)
Mon, 08 Aug 2016 09:39:16 GMT electron:stderr     at Module.load (module.js:458:32)
Mon, 08 Aug 2016 09:39:16 GMT electron:stderr     at tryModuleLoad (module.js:417:12)
Mon, 08 Aug 2016 09:39:16 GMT electron:stderr Xlib:  extension "RANDR" missing on display ":99".
Mon, 08 Aug 2016 09:39:16 GMT electron:stderr libudev: udev_has_devtmpfs: name_to_handle_at on /dev: Operation not permitted
```

**Comment by rrva** [comment]
Working workaround is:

```bash
cd /node_modules/nightmare && npm install --save
```

**Comment by rosshinkley** [comment]
Reproduction would be nice.  I can't reproduce locally.

**Comment by rrva** [comment]
Use https://github.com/rrva/nightmare-752-repro to reproduce

**Comment by albinekb** [comment]
Cannot reproduce using that repo:

```
~/Devel/Temp
❯ git clone git@github.com:rrva/nightmare-752-repro.git
Cloning into 'nightmare-752-repro'...
remote: Counting objects: 7, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 7 (delta 0), reused 7 (delta 0), pack-reused 0
Receiving objects: 100% (7/7), done.
Checking connectivity... done.

~/Devel/Temp
❯ cd nightmare-752-repro/

~/Devel/Temp/nightmare-752-repro master
❯ npm i

> electron-prebuilt@1.3.3 postinstall /Users/albinekb/Devel/Temp/nightmare-752-repro/node_modules/electron-prebuilt
> node install.js

Downloading electron-v1.3.3-darwin-x64.zip
[============================================>] 100.0% of 43.49 MB (2.42 MB/s)
app@1.0.0 /Users/albinekb/Devel/Temp/nightmare-752-repro
├─┬ nightmare@2.6.1
│ ├─┬ debug@2.2.0
│ │ └── ms@0.7.1
│ ├─┬ deep-defaults@1.0.4
│ │ └── lodash@3.0.1
│ ├─┬ defaults@1.0.3
│ │ └── clone@1.0.2
│ ├─┬ electron-prebuilt@1.3.3
│ │ ├─┬ electron-download@2.1.2
│ │ │ ├── home-path@1.0.3
│ │ │ ├── minimist@1.2.0
│ │ │ ├─┬ mv@2.1.1
│ │ │ │ ├── ncp@2.0.0
│ │ │ │ └─┬ rimraf@2.4.5
│ │ │ │   └── glob@6.0.4
│ │ │ ├─┬ nugget@1.6.2
│ │ │ │ ├─┬ pretty-bytes@1.0.4
│ │ │ │ │ ├── get-stdin@4.0.1
│ │ │ │ │ └─┬ meow@3.7.0
│ │ │ │ │   ├─┬ camelcase-keys@2.1.0
│ │ │ │ │   │ └── camelcase@2.1.1
│ │ │ │ │   ├── decamelize@1.2.0
│ │ │ │ │   ├─┬ loud-rejection@1.6.0
│ │ │ │ │   │ ├─┬ currently-unhandled@0.4.1
│ │ │ │ │   │ │ └── array-find-index@1.0.1
│ │ │ │ │   │ └── signal-exit@3.0.0
│ │ │ │ │   ├── map-obj@1.0.1
│ │ │ │ │   ├─┬ normalize-package-data@2.3.5
│ │ │ │ │   │ ├── hosted-git-info@2.1.5
│ │ │ │ │   │ ├─┬ is-builtin-module@1.0.0
│ │ │ │ │   │ │ └── builtin-modules@1.1.1
│ │ │ │ │   │ ├── semver@5.3.0
│ │ │ │ │   │ └─┬ validate-npm-package-license@3.0.1
│ │ │ │ │   │   ├─┬ spdx-correct@1.0.2
│ │ │ │ │   │   │ └── spdx-license-ids@1.2.2
│ │ │ │ │   │   └─┬ spdx-expression-parse@1.0.2
│ │ │ │ │   │     └── spdx-exceptions@1.0.5
│ │ │ │ │   ├─┬ read-pkg-up@1.0.1
│ │ │ │ │   │ ├─┬ find-up@1.1.2
│ │ │ │ │   │ │ └── path-exists@2.1.0
│ │ │ │ │   │ └─┬ read-pkg@1.1.0
│ │ │ │ │   │   ├─┬ load-json-file@1.1.0
│ │ │ │ │   │   │ ├── graceful-fs@4.1.5
│ │ │ │ │   │   │ ├─┬ parse-json@2.2.0
│ │ │ │ │   │   │ │ └─┬ error-ex@1.3.0
│ │ │ │ │   │   │ │   └── is-arrayish@0.2.1
│ │ │ │ │   │   │ ├── pify@2.3.0
│ │ │ │ │   │   │ └─┬ strip-bom@2.0.0
│ │ │ │ │   │   │   └── is-utf8@0.2.1
│ │ │ │ │   │   └── path-type@1.1.0
│ │ │ │ │   ├─┬ redent@1.0.0
│ │ │ │ │   │ ├─┬ indent-string@2.1.0
│ │ │ │ │   │ │ └─┬ repeating@2.0.1
│ │ │ │ │   │ │   └─┬ is-finite@1.0.1
│ │ │ │ │   │ │     └── number-is-nan@1.0.0
│ │ │ │ │   │ └── strip-indent@1.0.1
│ │ │ │ │   └── trim-newlines@1.0.0
│ │ │ │ ├─┬ progress-stream@1.2.0
│ │ │ │ │ ├── speedometer@0.1.4
│ │ │ │ │ └─┬ through2@0.2.3
│ │ │ │ │   ├─┬ readable-stream@1.1.14
│ │ │ │ │   │ └── isarray@0.0.1
│ │ │ │ │   └─┬ xtend@2.1.2
│ │ │ │ │     └── object-keys@0.4.0
│ │ │ │ ├─┬ request@2.74.0
│ │ │ │ │ ├── aws-sign2@0.6.0
│ │ │ │ │ ├── aws4@1.4.1
│ │ │ │ │ ├─┬ bl@1.1.2
│ │ │ │ │ │ └─┬ readable-stream@2.0.6
│ │ │ │ │ │   └── isarray@1.0.0
│ │ │ │ │ ├── caseless@0.11.0
│ │ │ │ │ ├─┬ combined-stream@1.0.5
│ │ │ │ │ │ └── delayed-stream@1.0.0
│ │ │ │ │ ├── extend@3.0.0
│ │ │ │ │ ├── forever-agent@0.6.1
│ │ │ │ │ ├─┬ form-data@1.0.0-rc4
│ │ │ │ │ │ └── async@1.5.2
│ │ │ │ │ ├─┬ har-validator@2.0.6
│ │ │ │ │ │ ├─┬ chalk@1.1.3
│ │ │ │ │ │ │ ├── ansi-styles@2.2.1
│ │ │ │ │ │ │ ├── escape-string-regexp@1.0.5
│ │ │ │ │ │ │ ├─┬ has-ansi@2.0.0
│ │ │ │ │ │ │ │ └── ansi-regex@2.0.0
│ │ │ │ │ │ │ ├── strip-ansi@3.0.1
│ │ │ │ │ │ │ └── supports-color@2.0.0
│ │ │ │ │ │ ├─┬ commander@2.9.0
│ │ │ │ │ │ │ └── graceful-readlink@1.0.1
│ │ │ │ │ │ ├─┬ is-my-json-valid@2.13.1
│ │ │ │ │ │ │ ├── generate-function@2.0.0
│ │ │ │ │ │ │ ├─┬ generate-object-property@1.2.0
│ │ │ │ │ │ │ │ └── is-property@1.0.2
│ │ │ │ │ │ │ ├── jsonpointer@2.0.0
│ │ │ │ │ │ │ └── xtend@4.0.1
│ │ │ │ │ │ └─┬ pinkie-promise@2.0.1
│ │ │ │ │ │   └── pinkie@2.0.4
│ │ │ │ │ ├─┬ hawk@3.1.3
│ │ │ │ │ │ ├── boom@2.10.1
│ │ │ │ │ │ ├── cryptiles@2.0.5
│ │ │ │ │ │ ├── hoek@2.16.3
│ │ │ │ │ │ └── sntp@1.0.9
│ │ │ │ │ ├─┬ http-signature@1.1.1
│ │ │ │ │ │ ├── assert-plus@0.2.0
│ │ │ │ │ │ ├─┬ jsprim@1.3.0
│ │ │ │ │ │ │ ├── extsprintf@1.0.2
│ │ │ │ │ │ │ ├── json-schema@0.2.2
│ │ │ │ │ │ │ └── verror@1.3.6
│ │ │ │ │ │ └─┬ sshpk@1.9.2
│ │ │ │ │ │   ├── asn1@0.2.3
│ │ │ │ │ │   ├── assert-plus@1.0.0
│ │ │ │ │ │   ├─┬ dashdash@1.14.0
│ │ │ │ │ │   │ └── assert-plus@1.0.0
│ │ │ │ │ │   ├── ecc-jsbn@0.1.1
│ │ │ │ │ │   ├─┬ getpass@0.1.6
│ │ │ │ │ │   │ └── assert-plus@1.0.0
│ │ │ │ │ │   ├── jodid25519@1.0.2
│ │ │ │ │ │   ├── jsbn@0.1.0
│ │ │ │ │ │   └── tweetnacl@0.13.3
│ │ │ │ │ ├── is-typedarray@1.0.0
│ │ │ │ │ ├── isstream@0.1.2
│ │ │ │ │ ├── json-stringify-safe@5.0.1
│ │ │ │ │ ├─┬ mime-types@2.1.11
│ │ │ │ │ │ └── mime-db@1.23.0
│ │ │ │ │ ├── node-uuid@1.4.7
│ │ │ │ │ ├── oauth-sign@0.8.2
│ │ │ │ │ ├── qs@6.2.1
│ │ │ │ │ ├── stringstream@0.0.5
│ │ │ │ │ ├── tough-cookie@2.3.1
│ │ │ │ │ └── tunnel-agent@0.4.3
│ │ │ │ ├── single-line-log@0.4.1
│ │ │ │ └── throttleit@0.0.2
│ │ │ ├── path-exists@1.0.0
│ │ │ └─┬ rc@1.1.6
│ │ │   ├── deep-extend@0.4.1
│ │ │   ├── ini@1.3.4
│ │ │   └── strip-json-comments@1.0.4
│ │ └─┬ extract-zip@1.5.0
│ │   ├─┬ concat-stream@1.5.0
│ │   │ ├─┬ readable-stream@2.0.6
│ │   │ │ └── isarray@1.0.0
│ │   │ └── typedarray@0.0.6
│ │   ├── debug@0.7.4
│ │   ├─┬ mkdirp@0.5.0
│ │   │ └── minimist@0.0.8
│ │   └─┬ yauzl@2.4.1
│ │     └─┬ fd-slicer@1.0.1
│ │       └── pend@1.2.0
│ ├─┬ enqueue@1.0.2
│ │ └── sliced@0.0.5
│ ├── function-source@0.1.0
│ ├── jsesc@0.5.0
│ ├─┬ minstache@1.2.0
│ │ └─┬ commander@1.0.4
│ │   └── keypress@0.1.0
│ ├─┬ mkdirp@0.5.1
│ │ └── minimist@0.0.8
│ ├── object-assign@4.1.0
│ ├─┬ once@1.3.3
│ │ └── wrappy@1.0.2
│ ├─┬ rimraf@2.5.4
│ │ └─┬ glob@7.0.5
│ │   ├── fs.realpath@1.0.0
│ │   ├── inflight@1.0.5
│ │   ├── inherits@2.0.1
│ │   ├─┬ minimatch@3.0.3
│ │   │ └─┬ brace-expansion@1.1.6
│ │   │   ├── balanced-match@0.4.2
│ │   │   └── concat-map@0.0.1
│ │   └── path-is-absolute@1.0.0
│ ├── sliced@1.0.1
│ └─┬ split2@2.1.0
│   └─┬ through2@2.0.1
│     ├─┬ readable-stream@2.0.6
│     │ ├── core-util-is@1.0.2
│     │ ├── isarray@1.0.0
│     │ ├── process-nextick-args@1.0.7
│     │ ├── string_decoder@0.10.31
│     │ └── util-deprecate@1.0.2
│     └── xtend@4.0.1
└─┬ vo@1.0.3
  ├── foreach@2.0.5
  ├── sliced@0.0.5
  └─┬ wrap-fn@0.1.5
    └── co@3.1.0

npm WARN app@1.0.0 No repository field.

~/Devel/Temp/nightmare-752-repro master*
❯ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	node_modules/

nothing added to commit but untracked files present (use "git add" to track)

~/Devel/Temp/nightmare-752-repro master*
❯ node app.js
sections []
null
```

**Comment by rrva** [comment]
@albinekb: To reproduce, you have to use the instructions in the README, i.e. run it in the environment provided in the Dockerfile. For example, this uses node v5.12.0 if this matters.

**Comment by rrva** [comment]
Since others have trouble reproducing I suspect it is something in my environment, thats why I provided the Dockerfile which reproduces it. There is nothing nonstandard about the environment, it uses the official node:5 docker image and adds the library dependencies which electron needs. When using nodejs 6.x image, I instead get problems when the dependency electron-prebuilt is installed: https://github.com/electron-userland/electron-prebuilt/issues/178 so I downgraded to node:5.

**Comment by albinekb** [comment]
When looking at the require error in electron-userland/electron-prebuilt#178 and here, it seems like it's not a problem with nightmare, maybe it's a problem with the prebuilt electron/electron itself. But most likely it's something with your setup  since it works fine on macOS & Ubuntu (headless on amazon)

**Comment by LinusU** [comment]
Seems like your npm isn't installing all dependencies...

**Comment by albinekb** [comment]
If you do a clean install, with your dockerfile and run `npm ls` in the project, and diff that with an install that's not in docker I'll think you'll see your problem 😃

**Comment by rrva** [comment]
The problem was that the application was installed in / and installing it in a separate directory fixed it.

See below changes. Was totally related to my env, so not a bug, closing.

https://github.com/rrva/nightmare-752-repro/pull/1/files

`npm ls -json` looked identical to my eyes both inside and outside the docker env though.

Thanks.

**Comment by albinekb** [comment]
Great that you got it working @rrva 😊
